# try except로 예외처리하기

## 정의
- 실행시간에 에러가 발생하여 코드가 중간되는 것을 방지할 떄 사용
```
try:
  <예외 발생 가능성이 있는 문장>
except <예외 종류>:
  <예외 처리 문장>
except (예외 1, 예외 2):
  <예외 처리 문장>
except 예외 as 인자:
  <예외 처리 문장>
else:
  <예외가 발생하지 않은 경우 수행될 문장>
finally:
  <예외 발생 유무에 상관없이 try블록 이후 수행할 문장>
```

## 예시
```python
def divide(a, b):
  return a / b

try:
  c = divide(5, 'string')
except ZeroDivisionError:
  print('두 번째 인자는 0이여서는 안됨')
except TypeError: ## 이 예외 형식으로 처리가 됨
  print('모든 인자는 숫자여야함')
except:
  print('음 무슨 에러인지 모르겠음')
```

## 예시2
```python
def divide(a, b):
  return a / b

try:
  c = divide(5, 'string')
except ZeroDivisionError:
  print('두 번째 인자는 0이여서는 안됨')
except TypeError: ## 이 예외 형식으로 처리가 됨
  print('모든 인자는 숫자여야함')
except:
  print('ZeroDivisionError, TypeError를 제외한 다른 에러')
else:
  print('Result: {0}'.format(c))
finally:
  print('항상 finally 블럭은 수행됨')
```